print("welcome to rock paper scissors game!!!")
a = input("Player 1 what do you choose ???      ")
if a == "":
	print("choose something")
else: 	
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
	print("no cheating!!!")
b = input("Player 2 what do you choose?????      ")
if b == "":
	print("choose something")
else:	
	if a == "rock" and b == "scissors":
		print("player 1 wins!!!!!!")
	elif a == "scissors" and b == "rock":
		print("player 2 wins!!!!!!")
	elif a == "paper" and b == "rock":
		print("player 1 wins!!!!!!")
	elif a == "rock" and b == "paper":
		print("player 2 wins!!!!!!")		
	elif a == "scissors" and b == "paper":
		print("player 1 wins!!!!!!")
	elif a == "paper" and b == "scissors":
		print("Player ")	
